--다음 조건에 맞는 테이블을 생성하세요.

--테이블명 : TBL_BOOK

CREATE SEQUENCE SEQ_BOOK;
CREATE TABLE TBL_BOOK(
	ID NUMBER CONSTRAINT PK_BOOK PRIMARY KEY,
	BOOK_TITLE VARCHAR2(255) NOT NULL UNIQUE,
	BOOK_AUTHOR VARCHAR2(255) NOT NULL,
	BOOK_PRICE NUMBER DEFAULT 0,
	BOOK_CREAT_AT DATE DEFAULT CURRENT_TIMESTAMP
);

--다음 조건의 테이블을 생성하세요.

--테이블명 : TBL_STUDENT

CREATE SEQUENCE SEQ_STUDENT;
CREATE TABLE TBL_STUDENT(
	ID NUMBER CONSTRAINT PK_STUDENT PRIMARY KEY,
	STUDENT_NAME VARCHAR2(255) NOT NULL,
	STUDENT_EMAIL VARCHAR2(255) NOT NULL UNIQUE,
	STUDENT_AGE NUMBER NOT NULL
);

-- TBL_BOOK 테이블에 다음 컬럼을 추가하세요.
-- BOOK_STOCK NUMBER DEFAULT 0
ALTER TABLE TBL_BOOK ADD BOOK_STOCK NUMBER DEFAULT 0;

-- TBL_BOOK 테이블에서
-- BOOK_PRICE 타입을 VARCHAR2(255) 로 변경하세요.

ALTER TABLE TBL_BOOK MODIFY BOOK_PRICE VARCHAR(255);

-- TBL_BOOK 테이블에서

-- BOOK_AUTHOR 컬럼 이름을
-- BOOK_WRITER로 변경하세요.

ALTER TABLE TBL_BOOK RENAME COLUMN BOOK_AUTHOR TO BOOK_WRITER;

-- TBL_BOOK 테이블에서
-- BOOK_STOCK 컬럼 삭제

ALTER TABLE TBL_BOOK DROP COLUMN BOOK_STOCK;

-- TBL_STUDENT 테이블에서
-- STUDENT_EMAIL UNIQUE 제약조건 추가
-- 제약조건 이름 UK_STUDENT_EMAIL
ALTER TABLE TBL_STUDENT DROP CONSTRAINT STUDENT_EMAIL;
ALTER TABLE TBL_STUDENT ADD CONSTRAINT UK_STUDENT_EMAIL UNIQUE (STUDENT_EMAIL);

--다음 조건으로 테이블을 만드세요.
--유저 테이블
--테이블명 : TBL_MEMBER
CREATE SEQUENCE SEQ_MEMBER;
CREATE TABLE TBL_MEMBER(
	ID NUMBER CONSTRAINT PK_MEMBER PRIMARY KEY,
	MEMBER_NAME VARCHAR2(255) NOT NULL,
	MEMBER_PHONE VARCHAR2(255)
);

--주문 테이블을 만드세요.
--테이블명 : TBL_MEMBER_ORDER
CREATE SEQUENCE SEQ_MEMBER_ORDER;
CREATE TABLE TBL_MEMBER_ORDER(
	ID NUMBER CONSTRAINT PK_MEMBER_ORDER PRIMARY KEY,
	MEMBER_ORDER_NAME VARCHAR2(255),
	MEMBER_ID NUMBER,
	CONSTRAINT FK_MEMBER_ORDER FOREIGN KEY(MEMBER_ID)
	REFERENCES TBL_MEMBER(ID)
);

-- 다음 구조로 정규화 테이블을 만드세요.
-- TBL_CATEGORY

CREATE SEQUENCE SEQ_CATEGORY;
CREATE TABLE TBL_CATEGORY(
	ID NUMBER CONSTRAINT PK_CATEGORY PRIMARY KEY,
	CATEGORY_NAME VARCHAR2(255) UNIQUE
);

-- 상품 테이블 TBL_ITEM

CREATE SEQUENCE SEQ_ITEM;
CREATE TABLE TBL_ITEM(
	ID NUMBER CONSTRAINT PK_ITEM PRIMARY KEY,
	ITEM_NAME VARCHAR2(255) NOT NULL,
	ITEM_PRICE NUMBER DEFAULT 0,
	CATEGORY_ID NUMBER,
	CONSTRAINT FK_ITEM FOREIGN KEY(CATEGORY_ID)
	REFERENCES TBL_CATEGORY(ID)
);

-- 다음 조건의 테이블을 만드세요.
-- 테이블명
-- TBL_MOVIE

CREATE SEQUENCE SEQ_MOVIE;
CREATE TABLE TBL_MOVIE(
	ID NUMBER CONSTRAINT PK_MOVIE PRIMARY KEY,
	MOVIE_TITLE VARCHAR2(255) NOT NULL,
	MOVIE_GENRE VARCHAR2(255),
	MOVIE_PRICE NUMBER DEFAULT 10000,
	MOVIE_CREATE_AT DATE DEFAULT CURRENT_TIMESTAMP
);

-- TBL_MOVIE 테이블에서
-- MOVIE_GENRE 컬럼 이름을
-- MOVIE_CATEGORY 로 변경

ALTER TABLE TBL_MOVIE RENAME COLUMN MOVIE_GENRE TO MOVIE_CATEGORY;

-- TBL_MOVIE 테이블에 컬럼 추가
-- MOVIE_STOCK NUMBER DEFAULT 0

ALTER TABLE TBL_MOVIE ADD MOVIE_STOCK NUMBER DEFAULT 0;

-- TBL_MOVIE 테이블에서
-- MOVIE_PRICE 타입을 VARCHAR2(255) 로 변경

ALTER TABLE TBL_MOVIE MODIFY MOVIE_PRICE VARCHAR2(255);

-- 다음 테이블 생성
-- 테이블명 TBL_CUSTOMER

CREATE SEQUENCE SEQ_CUSTOMER;
CREATE TABLE TBL_CUSTOMER(
	ID NUMBER CONSTRAINT PK_CUSTOMER PRIMARY KEY,
	COSTOMER_EMAIL VARCHAR2(255) UNIQUE NOT NULL,
	CUSTOMER_NAME VARCHAR2(255) NOT NULL,
	COSTOMER_PHONE VARCHAR2(255)
);

-- 주문 테이블 생성
-- 테이블명 TBL_MOVIE_ORDER

CREATE SEQUENCE SEQ_MOVIE_ORDER;
CREATE TABLE TBL_MOVIE_ORDER(
	ID NUMBER CONSTRAINT PK_MOVIE_ORDER PRIMARY KEY,
	ORDER_COUNT NUMBER DEFAULT 1,
	CUSTOMER_ID NUMBER,
	CONSTRAINT TK_MOVIE_ORDER FOREIGN KEY(CUSTOMER_ID)
	REFERENCES TBL_CUSTOMER(ID)
);

-- 다음 테이블을 생성하세요.
-- 테이블명 TBL_GAME

CREATE SEQUENCE SEQ_GAME;
CREATE TABLE TBL_GAME(
	ID NUMBER CONSTRAINT PK_GAME PRIMARY KEY,
	GAME_NAME VARCHAR2(255) NOT NULL,
	GAME_PRICE NUMBER DEFAULT 50000,
	GAME_COMPANY VARCHAR2(255) NOT NULL,
	GAME_CREATE_AT DATE DEFAULT CURRENT_TIMESTAMP
);

-- TBL_GAME 테이블에서

-- GAME_COMPANY

-- 컬럼 이름을 GAME_DEVELOPER 변경

ALTER TABLE TBL_GAME RENAME COLUMN GAME_COMPANY TO GAME_DEVELOPER;

-- TBL_GAME 테이블에 컬럼 추가
-- GAME_STOCK NUMBER DEFAULT 10

ALTER TABLE TBL_GAME ADD GAME_STOCK NUMBER DEFAULT 10;

-- TBL_GAME 테이블에서
-- GAME_PRICE 타입을 VARCHAR2(255) 로 변경

ALTER TABLE TBL_GAME MODIFY GAME_PRICE VARCHAR2(255);

-- 다음 테이블 생성
-- 테이블명 TBL_PLAYER

CREATE SEQUENCE SEQ_PLAYER;
CREATE TABLE TBL_PLAYER(
	ID NUMBER CONSTRAINT PK_PLAYER PRIMARY KEY,
	PLAYER_EMAIL VARCHAR2(255) UNIQUE NOT NULL,
	PLAYER_NAME VARCHAR2(255) NOT NULL,
	PLAYER_LEVEL NUMBER DEFAULT 1
);

-- 구매 테이블 생성

-- 테이블명 TBL_GAME_ORDER

CREATE SEQUENCE SEQ_GAME_ORDER;
CREATE TABLE TBL_GAME_ORDER(
	ID NUMBER CONSTRAINT PK_GAME_ORDER PRIMARY KEY,
	GAME_ORDER_COUNT NUMBER DEFAULT 1,
	PLAYER_ID NUMBER,
	CONSTRAINT FK_GAME_ORDER_PLAYER FOREIGN KEY(PLAYER_ID)
	REFERENCES TBL_PLAYER(ID)
);



